package com.mycompany.perpusdata;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class anggotadelete extends javax.swing.JFrame {

    /**
     * Creates new form anggotadelete
     */
    public anggotadelete() {
        initComponents();
        getContentPane().setBackground(Color.decode("0xFFFFFFF"));
        setDefaultCloseOperation(anggotadelete.DISPOSE_ON_CLOSE);
        hasil.setDefaultCloseOperation(hasil.DISPOSE_ON_CLOSE);
        konfirmasi.setDefaultCloseOperation(konfirmasi.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasil = new javax.swing.JDialog();
        home1 = new javax.swing.JButton();
        anggota1 = new javax.swing.JButton();
        buku1 = new javax.swing.JButton();
        peminjaman1 = new javax.swing.JButton();
        pengembalian1 = new javax.swing.JButton();
        statkini1 = new javax.swing.JButton();
        hover1 = new javax.swing.JPanel();
        bg3 = new javax.swing.JPanel();
        kembali1 = new javax.swing.JButton();
        labeldelete1 = new javax.swing.JLabel();
        labelberhasil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labeldelete2 = new javax.swing.JLabel();
        lagi = new javax.swing.JButton();
        konfirmasi = new javax.swing.JDialog();
        home2 = new javax.swing.JButton();
        anggota2 = new javax.swing.JButton();
        buku2 = new javax.swing.JButton();
        peminjaman2 = new javax.swing.JButton();
        pengembalian2 = new javax.swing.JButton();
        statkini2 = new javax.swing.JButton();
        bg4 = new javax.swing.JPanel();
        kembali2 = new javax.swing.JButton();
        hover2 = new javax.swing.JPanel();
        labelupdate = new javax.swing.JLabel();
        labeldelete3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        labellanjutkan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonkembali = new javax.swing.JButton();
        buttonlanjutkan = new javax.swing.JButton();
        labelketentuan2 = new javax.swing.JLabel();
        labelketentuan3 = new javax.swing.JLabel();
        hasilemail = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labeljenke = new javax.swing.JLabel();
        labelalamat = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        labelida = new javax.swing.JLabel();
        hasilida = new javax.swing.JLabel();
        hasilnama = new javax.swing.JLabel();
        hasiljenke = new javax.swing.JLabel();
        hasilalamat = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        anggota = new javax.swing.JButton();
        buku = new javax.swing.JButton();
        peminjaman = new javax.swing.JButton();
        pengembalian = new javax.swing.JButton();
        statkini = new javax.swing.JButton();
        hover = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        kembali = new javax.swing.JButton();
        labelmasukkanid = new javax.swing.JLabel();
        cekida = new javax.swing.JTextField();
        buttoncek = new javax.swing.JButton();
        labeldelete = new javax.swing.JLabel();

        hasil.setMinimumSize(new java.awt.Dimension(830, 450));
        hasil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home1.setBackground(new java.awt.Color(241, 244, 246));
        home1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home1.setForeground(new java.awt.Color(255, 255, 255));
        home1.setText("HOME");
        home1.setBorderPainted(false);
        home1.setContentAreaFilled(false);
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota1.setBackground(new java.awt.Color(241, 244, 246));
        anggota1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota1.setForeground(new java.awt.Color(255, 255, 255));
        anggota1.setText("ANGGOTA");
        anggota1.setBorderPainted(false);
        anggota1.setContentAreaFilled(false);
        anggota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(anggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku1.setBackground(new java.awt.Color(241, 244, 246));
        buku1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku1.setForeground(new java.awt.Color(255, 255, 255));
        buku1.setText("BUKU");
        buku1.setBorderPainted(false);
        buku1.setContentAreaFilled(false);
        buku1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman1.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman1.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman1.setText("PEMINJAMAN");
        peminjaman1.setBorderPainted(false);
        peminjaman1.setContentAreaFilled(false);
        peminjaman1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(peminjaman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian1.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian1.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian1.setText("PENGEMBALIAN");
        pengembalian1.setBorderPainted(false);
        pengembalian1.setContentAreaFilled(false);
        pengembalian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(pengembalian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini1.setBackground(new java.awt.Color(241, 244, 246));
        statkini1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini1.setForeground(new java.awt.Color(255, 255, 255));
        statkini1.setText("STATUS TERKINI");
        statkini1.setBorderPainted(false);
        statkini1.setContentAreaFilled(false);
        statkini1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini1ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(statkini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        hover1.setBackground(new java.awt.Color(190, 196, 205));
        hasil.getContentPane().add(hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        bg3.setBackground(new java.awt.Color(155, 164, 180));
        bg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali1.setForeground(new java.awt.Color(255, 255, 255));
        kembali1.setText("logout");
        kembali1.setBorderPainted(false);
        kembali1.setContentAreaFilled(false);
        kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ActionPerformed(evt);
            }
        });
        bg3.add(kembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hasil.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        labeldelete1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labeldelete1.setForeground(new java.awt.Color(190, 196, 205));
        labeldelete1.setText("MENGHAPUS DATA");
        hasil.getContentPane().add(labeldelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        labelberhasil.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        labelberhasil.setForeground(new java.awt.Color(155, 164, 180));
        labelberhasil.setText("DATA BERHASIL DIHAPUS");
        hasil.getContentPane().add(labelberhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 390, -1));
        hasil.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 360, 10));

        labeldelete2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labeldelete2.setForeground(new java.awt.Color(155, 164, 180));
        labeldelete2.setText("DELETE");
        hasil.getContentPane().add(labeldelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        lagi.setBackground(new java.awt.Color(216, 219, 227));
        lagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lagi.setForeground(new java.awt.Color(155, 164, 180));
        lagi.setText("Delete Data Lain");
        lagi.setBorder(null);
        lagi.setBorderPainted(false);
        lagi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lagiActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(lagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, 40));

        konfirmasi.setBackground(new java.awt.Color(255, 255, 255));
        konfirmasi.setMinimumSize(new java.awt.Dimension(830, 450));
        konfirmasi.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home2.setBackground(new java.awt.Color(241, 244, 246));
        home2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home2.setForeground(new java.awt.Color(255, 255, 255));
        home2.setText("HOME");
        home2.setBorderPainted(false);
        home2.setContentAreaFilled(false);
        home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota2.setBackground(new java.awt.Color(241, 244, 246));
        anggota2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota2.setForeground(new java.awt.Color(255, 255, 255));
        anggota2.setText("ANGGOTA");
        anggota2.setBorderPainted(false);
        anggota2.setContentAreaFilled(false);
        anggota2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(anggota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku2.setBackground(new java.awt.Color(241, 244, 246));
        buku2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku2.setForeground(new java.awt.Color(255, 255, 255));
        buku2.setText("BUKU");
        buku2.setBorderPainted(false);
        buku2.setContentAreaFilled(false);
        buku2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(buku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman2.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman2.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman2.setText("PEMINJAMAN");
        peminjaman2.setBorderPainted(false);
        peminjaman2.setContentAreaFilled(false);
        peminjaman2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(peminjaman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian2.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian2.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian2.setText("PENGEMBALIAN");
        pengembalian2.setBorderPainted(false);
        pengembalian2.setContentAreaFilled(false);
        pengembalian2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(pengembalian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini2.setBackground(new java.awt.Color(241, 244, 246));
        statkini2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini2.setForeground(new java.awt.Color(255, 255, 255));
        statkini2.setText("STATUS TERKINI");
        statkini2.setBorderPainted(false);
        statkini2.setContentAreaFilled(false);
        statkini2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini2ActionPerformed(evt);
            }
        });
        konfirmasi.getContentPane().add(statkini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        bg4.setBackground(new java.awt.Color(155, 164, 180));
        bg4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali2.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali2.setForeground(new java.awt.Color(255, 255, 255));
        kembali2.setText("logout");
        kembali2.setBorderPainted(false);
        kembali2.setContentAreaFilled(false);
        kembali2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali2ActionPerformed(evt);
            }
        });
        bg4.add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover2.setBackground(new java.awt.Color(190, 196, 205));
        bg4.add(hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        konfirmasi.getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        labelupdate.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelupdate.setForeground(new java.awt.Color(190, 196, 205));
        labelupdate.setText("MENGHAPUS DATA");
        konfirmasi.getContentPane().add(labelupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        labeldelete3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labeldelete3.setForeground(new java.awt.Color(155, 164, 180));
        labeldelete3.setText("DELETE");
        konfirmasi.getContentPane().add(labeldelete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));
        konfirmasi.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 220, 10));

        jPanel1.setBackground(new java.awt.Color(155, 164, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellanjutkan.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        labellanjutkan.setForeground(new java.awt.Color(255, 255, 255));
        labellanjutkan.setText("LANJUTKAN?");
        jPanel1.add(labellanjutkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pastikan tidak ada kekeliruan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Periksa lagi data tujuan anda dan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        buttonkembali.setBackground(new java.awt.Color(190, 196, 205));
        buttonkembali.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttonkembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonkembali.setText("Kembali");
        buttonkembali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonkembali.setContentAreaFilled(false);
        buttonkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        buttonlanjutkan.setBackground(new java.awt.Color(190, 196, 205));
        buttonlanjutkan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttonlanjutkan.setForeground(new java.awt.Color(255, 255, 255));
        buttonlanjutkan.setText("Lanjutkan");
        buttonlanjutkan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonlanjutkan.setContentAreaFilled(false);
        buttonlanjutkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlanjutkanActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlanjutkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, 30));

        konfirmasi.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 270, 120));

        labelketentuan2.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan2.setText("dari buku yang telah dipilih");
        konfirmasi.getContentPane().add(labelketentuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        labelketentuan3.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan3.setText("* Akan menghapus semua data");
        konfirmasi.getContentPane().add(labelketentuan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        hasilemail.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        hasilemail.setForeground(new java.awt.Color(155, 164, 180));
        hasilemail.setText("ID Anggota");
        konfirmasi.getContentPane().add(hasilemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 350, 40));

        labelnama.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelnama.setForeground(new java.awt.Color(155, 164, 180));
        labelnama.setText("Nama              :");
        konfirmasi.getContentPane().add(labelnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 40));

        labeljenke.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labeljenke.setForeground(new java.awt.Color(155, 164, 180));
        labeljenke.setText("Jenis Kelamin:");
        konfirmasi.getContentPane().add(labeljenke, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, 40));

        labelalamat.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelalamat.setForeground(new java.awt.Color(155, 164, 180));
        labelalamat.setText("Alamat            :");
        konfirmasi.getContentPane().add(labelalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 40));

        labelemail.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelemail.setForeground(new java.awt.Color(155, 164, 180));
        labelemail.setText("Email               :");
        konfirmasi.getContentPane().add(labelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 40));

        labelida.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelida.setForeground(new java.awt.Color(155, 164, 180));
        labelida.setText("ID Anggota    :");
        konfirmasi.getContentPane().add(labelida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 86, -1, 40));

        hasilida.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        hasilida.setForeground(new java.awt.Color(155, 164, 180));
        hasilida.setText("ID Anggota");
        konfirmasi.getContentPane().add(hasilida, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 350, 30));

        hasilnama.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        hasilnama.setForeground(new java.awt.Color(155, 164, 180));
        hasilnama.setText("ID Anggota");
        konfirmasi.getContentPane().add(hasilnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 350, 40));

        hasiljenke.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        hasiljenke.setForeground(new java.awt.Color(155, 164, 180));
        hasiljenke.setText("ID Anggota");
        konfirmasi.getContentPane().add(hasiljenke, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 350, 40));

        hasilalamat.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        hasilalamat.setForeground(new java.awt.Color(155, 164, 180));
        hasilalamat.setText("ID Anggota");
        konfirmasi.getContentPane().add(hasilalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 350, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(241, 244, 246));
        home.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota.setBackground(new java.awt.Color(241, 244, 246));
        anggota.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota.setForeground(new java.awt.Color(255, 255, 255));
        anggota.setText("ANGGOTA");
        anggota.setBorderPainted(false);
        anggota.setContentAreaFilled(false);
        anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku.setBackground(new java.awt.Color(241, 244, 246));
        buku.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku.setForeground(new java.awt.Color(255, 255, 255));
        buku.setText("BUKU");
        buku.setBorderPainted(false);
        buku.setContentAreaFilled(false);
        buku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuActionPerformed(evt);
            }
        });
        getContentPane().add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman.setText("PEMINJAMAN");
        peminjaman.setBorderPainted(false);
        peminjaman.setContentAreaFilled(false);
        peminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian.setText("PENGEMBALIAN");
        pengembalian.setBorderPainted(false);
        pengembalian.setContentAreaFilled(false);
        pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini.setBackground(new java.awt.Color(241, 244, 246));
        statkini.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini.setForeground(new java.awt.Color(255, 255, 255));
        statkini.setText("STATUS TERKINI");
        statkini.setBorderPainted(false);
        statkini.setContentAreaFilled(false);
        statkini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkiniActionPerformed(evt);
            }
        });
        getContentPane().add(statkini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        hover.setBackground(new java.awt.Color(190, 196, 205));
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        bg2.setBackground(new java.awt.Color(155, 164, 180));
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("logout");
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        bg2.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 410));

        labelmasukkanid.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        labelmasukkanid.setForeground(new java.awt.Color(155, 164, 180));
        labelmasukkanid.setText("Masukkan ID Anggota");
        getContentPane().add(labelmasukkanid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        cekida.setBackground(new java.awt.Color(216, 219, 227));
        cekida.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cekida.setForeground(new java.awt.Color(155, 164, 180));
        cekida.setBorder(null);
        cekida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cekida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekidaActionPerformed(evt);
            }
        });
        getContentPane().add(cekida, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 40));

        buttoncek.setBackground(new java.awt.Color(155, 164, 180));
        buttoncek.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        buttoncek.setForeground(new java.awt.Color(255, 255, 255));
        buttoncek.setText("Cek");
        buttoncek.setBorder(null);
        buttoncek.setBorderPainted(false);
        buttoncek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncekActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncek, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 80, 30));

        labeldelete.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labeldelete.setForeground(new java.awt.Color(190, 196, 205));
        labeldelete.setText("MENGHAPUS DATA");
        getContentPane().add(labeldelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuActionPerformed
        // TODO add your handling code here:
        dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_bukuActionPerformed

    private void cekidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekidaActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanActionPerformed
        // TODO add your handling code here:
        dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_peminjamanActionPerformed

    private void pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianActionPerformed
        // TODO add your handling code here:
        dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalianActionPerformed

    private void statkiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkiniActionPerformed
        // TODO add your handling code here:
        dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkiniActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    private void buttoncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncekActionPerformed
        // TODO add your handling code here:
        try {
           CRUDAnggota CrudA = new CRUDAnggota();
           int id_anggota = Integer.parseInt(cekida.getText());
            
            CrudA.ida(id_anggota);
            if (CrudA.ida(id_anggota)){
                dispose();
                this.tampilDataAnggota(id_anggota);
                konfirmasi.setVisible(true);
                konfirmasi.getContentPane().setBackground(Color.decode("0xFFFFFF"));
            } else {
                JOptionPane.showMessageDialog(this, "ID Anggota tidak ditemukan!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch(SQLException e) {
            e.printStackTrace();
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Masukkan angka atau integer saja", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttoncekActionPerformed

    private void kembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembali1ActionPerformed

    private void anggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home1ActionPerformed

    private void buku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku1ActionPerformed

    private void peminjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_peminjaman1ActionPerformed

    private void pengembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian1ActionPerformed

    private void statkini1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini1ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini1ActionPerformed

    private void lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lagiActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new anggotadelete().setVisible(true);
    }//GEN-LAST:event_lagiActionPerformed

    private void kembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembali2ActionPerformed

    private void buttonkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkembaliActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new anggotadelete().setVisible(true);
    }//GEN-LAST:event_buttonkembaliActionPerformed

    private void buttonlanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlanjutkanActionPerformed
        // TODO add your handling code here:
            CRUDAnggota CrudA = new CRUDAnggota();
            int id_anggota = Integer.parseInt(cekida.getText());
            CrudA.delete(id_anggota);
            konfirmasi.dispose();
            hasil.setVisible(true);
            hasil.getContentPane().setBackground(Color.decode("0xFFFFFF"));
    }//GEN-LAST:event_buttonlanjutkanActionPerformed

    private void anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaActionPerformed
        // TODO add your handling code here:
        dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggotaActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home2ActionPerformed

    private void anggota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota2ActionPerformed

    private void buku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku2ActionPerformed

    private void peminjaman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_peminjaman2ActionPerformed

    private void pengembalian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian2ActionPerformed

    private void statkini2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini2ActionPerformed
        // TODO add your handling code here:
        konfirmasi.dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini2ActionPerformed
    
    public void tampilDataAnggota(int id_anggota){
        String query = "SELECT id_anggota, nama, jenis_kelamin, alamat, email FROM anggota WHERE id_anggota = ?";
        try{
            Koneksi konek = new Koneksi();
            Connection koneksi = konek.buka();
            PreparedStatement preparedStatement = koneksi.prepareStatement(query);
            preparedStatement.setInt(1, id_anggota);
            
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    // Ambil data dari ResultSet dan set pada JLabels
                    hasilida.setText("" + resultSet.getInt("id_anggota"));
                    hasilnama.setText(resultSet.getString("nama"));
                    hasiljenke.setText(resultSet.getString("jenis_kelamin"));
                    hasilalamat.setText(resultSet.getString("alamat"));
                    hasilemail.setText(resultSet.getString("email"));
                } else {
                    System.out.println("Data tidak ditemukan.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void anggotadelete(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggotadelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggotadelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggotadelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggotadelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggotadelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anggota;
    private javax.swing.JButton anggota1;
    private javax.swing.JButton anggota2;
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel bg4;
    private javax.swing.JButton buku;
    private javax.swing.JButton buku1;
    private javax.swing.JButton buku2;
    private javax.swing.JButton buttoncek;
    private javax.swing.JButton buttonkembali;
    private javax.swing.JButton buttonlanjutkan;
    private javax.swing.JTextField cekida;
    private javax.swing.JDialog hasil;
    private javax.swing.JLabel hasilalamat;
    private javax.swing.JLabel hasilemail;
    private javax.swing.JLabel hasilida;
    private javax.swing.JLabel hasiljenke;
    private javax.swing.JLabel hasilnama;
    private javax.swing.JButton home;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JPanel hover;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton kembali;
    private javax.swing.JButton kembali1;
    private javax.swing.JButton kembali2;
    private javax.swing.JDialog konfirmasi;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labelberhasil;
    private javax.swing.JLabel labeldelete;
    private javax.swing.JLabel labeldelete1;
    private javax.swing.JLabel labeldelete2;
    private javax.swing.JLabel labeldelete3;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labelida;
    private javax.swing.JLabel labeljenke;
    private javax.swing.JLabel labelketentuan2;
    private javax.swing.JLabel labelketentuan3;
    private javax.swing.JLabel labellanjutkan;
    private javax.swing.JLabel labelmasukkanid;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelupdate;
    private javax.swing.JButton lagi;
    private javax.swing.JButton peminjaman;
    private javax.swing.JButton peminjaman1;
    private javax.swing.JButton peminjaman2;
    private javax.swing.JButton pengembalian;
    private javax.swing.JButton pengembalian1;
    private javax.swing.JButton pengembalian2;
    private javax.swing.JButton statkini;
    private javax.swing.JButton statkini1;
    private javax.swing.JButton statkini2;
    // End of variables declaration//GEN-END:variables
}
