/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpusdata;


import java.awt.Color;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
/**
 *
 * @author ASUS
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
        getContentPane().setBackground(Color.decode("0xFFFFFFF"));
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsn = new javax.swing.JLabel();
        labelPsw = new javax.swing.JLabel();
        inputUsn = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        inputPsw = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        labelAP = new javax.swing.JLabel();
        labelUNS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelUsn.setForeground(new java.awt.Color(155, 164, 180));
        labelUsn.setText("Username");
        getContentPane().add(labelUsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 187, -1, -1));

        labelPsw.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelPsw.setForeground(new java.awt.Color(155, 164, 180));
        labelPsw.setText("Password");
        getContentPane().add(labelPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 248, -1, -1));

        inputUsn.setBackground(new java.awt.Color(227, 230, 237));
        inputUsn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        inputUsn.setForeground(new java.awt.Color(169, 180, 200));
        inputUsn.setToolTipText("");
        inputUsn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(222, 229, 232), new java.awt.Color(222, 229, 232)), null));
        getContentPane().add(inputUsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 181, 224, 35));

        labelLogin.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(155, 164, 180));
        labelLogin.setText("LOGIN");
        getContentPane().add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 81, -1, -1));

        buttonLogin.setBackground(new java.awt.Color(169, 180, 200));
        buttonLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(169, 180, 200));
        buttonLogin.setText("login");
        buttonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLogin.setBorderPainted(false);
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 318, 96, 29));

        inputPsw.setBackground(new java.awt.Color(227, 230, 237));
        inputPsw.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        inputPsw.setForeground(new java.awt.Color(169, 180, 200));
        inputPsw.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(222, 229, 232), new java.awt.Color(222, 229, 232)), null));
        getContentPane().add(inputPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 242, 224, 35));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 144, 357, 10));

        labelAP.setForeground(new java.awt.Color(169, 180, 200));
        labelAP.setText("Admin Perpustakaan");
        getContentPane().add(labelAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        labelUNS.setForeground(new java.awt.Color(169, 180, 200));
        labelUNS.setText("Universitas Sebelas Maret");
        getContentPane().add(labelUNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        try {
            LoginClass tesLogin = new LoginClass();
            String username = String.valueOf(inputUsn.getText());
            String password = String.valueOf(inputPsw.getText());
            
            tesLogin.login(username, password);
            if (tesLogin.login(username, password)){
                dispose();
                new mainpage().setVisible(true);
            } else {
                //tampilkan bahwa username atau password salah
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void login(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPasswordField inputPsw;
    private javax.swing.JTextField inputUsn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAP;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPsw;
    private javax.swing.JLabel labelUNS;
    private javax.swing.JLabel labelUsn;
    // End of variables declaration//GEN-END:variables
}
