package com.mycompany.perpusdata;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class pinjampage extends javax.swing.JFrame {

    /**
     * Creates new form pinjampage
     */
    public pinjampage() {
        initComponents();
        getContentPane().setBackground(Color.decode("0xFFFFFFF"));
        setDefaultCloseOperation(pinjampage.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasil = new javax.swing.JDialog();
        labelpinjam3 = new javax.swing.JLabel();
        home2 = new javax.swing.JButton();
        anggota2 = new javax.swing.JButton();
        buku2 = new javax.swing.JButton();
        peminjaman2 = new javax.swing.JButton();
        pengembalian2 = new javax.swing.JButton();
        statkini2 = new javax.swing.JButton();
        riwayat2 = new javax.swing.JButton();
        bg4 = new javax.swing.JPanel();
        kembali2 = new javax.swing.JButton();
        hover2 = new javax.swing.JPanel();
        labelberhasil = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelpinjam4 = new javax.swing.JLabel();
        labelberhasil1 = new javax.swing.JLabel();
        lagi = new javax.swing.JButton();
        labeltenggat = new javax.swing.JLabel();
        tenggat = new javax.swing.JLabel();
        labelpinjam1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelpinjam2 = new javax.swing.JLabel();
        home1 = new javax.swing.JButton();
        anggota1 = new javax.swing.JButton();
        buku1 = new javax.swing.JButton();
        peminjaman1 = new javax.swing.JButton();
        pengembalian1 = new javax.swing.JButton();
        statkini1 = new javax.swing.JButton();
        riwayat1 = new javax.swing.JButton();
        bg3 = new javax.swing.JPanel();
        kembali1 = new javax.swing.JButton();
        hover1 = new javax.swing.JPanel();
        labelidb = new javax.swing.JLabel();
        labelidba = new javax.swing.JLabel();
        inputidb = new javax.swing.JTextField();
        inputida = new javax.swing.JTextField();
        buttoncek = new javax.swing.JButton();

        hasil.setMaximumSize(new java.awt.Dimension(830, 450));
        hasil.setMinimumSize(new java.awt.Dimension(830, 450));
        hasil.setPreferredSize(new java.awt.Dimension(830, 450));
        hasil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpinjam3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpinjam3.setForeground(new java.awt.Color(190, 196, 205));
        labelpinjam3.setText("PEMINJAMAN BUKU");
        hasil.getContentPane().add(labelpinjam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        home2.setBackground(new java.awt.Color(241, 244, 246));
        home2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home2.setForeground(new java.awt.Color(255, 255, 255));
        home2.setText("HOME");
        home2.setBorderPainted(false);
        home2.setContentAreaFilled(false);
        home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota2.setBackground(new java.awt.Color(241, 244, 246));
        anggota2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota2.setForeground(new java.awt.Color(255, 255, 255));
        anggota2.setText("ANGGOTA");
        anggota2.setBorderPainted(false);
        anggota2.setContentAreaFilled(false);
        anggota2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(anggota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku2.setBackground(new java.awt.Color(241, 244, 246));
        buku2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku2.setForeground(new java.awt.Color(255, 255, 255));
        buku2.setText("BUKU");
        buku2.setBorderPainted(false);
        buku2.setContentAreaFilled(false);
        buku2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(buku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman2.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman2.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman2.setText("PEMINJAMAN");
        peminjaman2.setBorderPainted(false);
        peminjaman2.setContentAreaFilled(false);
        peminjaman2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(peminjaman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian2.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian2.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian2.setText("PENGEMBALIAN");
        pengembalian2.setBorderPainted(false);
        pengembalian2.setContentAreaFilled(false);
        pengembalian2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(pengembalian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini2.setBackground(new java.awt.Color(241, 244, 246));
        statkini2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini2.setForeground(new java.awt.Color(255, 255, 255));
        statkini2.setText("STATUS TERKINI");
        statkini2.setBorderPainted(false);
        statkini2.setContentAreaFilled(false);
        statkini2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(statkini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        riwayat2.setBackground(new java.awt.Color(241, 244, 246));
        riwayat2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        riwayat2.setForeground(new java.awt.Color(255, 255, 255));
        riwayat2.setText("RIWAYAT");
        riwayat2.setBorderPainted(false);
        riwayat2.setContentAreaFilled(false);
        riwayat2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(riwayat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 270, 150, -1));

        bg4.setBackground(new java.awt.Color(155, 164, 180));
        bg4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali2.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali2.setForeground(new java.awt.Color(255, 255, 255));
        kembali2.setText("kembali");
        kembali2.setBorderPainted(false);
        kembali2.setContentAreaFilled(false);
        kembali2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg4.add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover2.setBackground(new java.awt.Color(190, 196, 205));
        hover2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg4.add(hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        hasil.getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        labelberhasil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelberhasil.setForeground(new java.awt.Color(155, 164, 180));
        labelberhasil.setText("DIPINJAM");
        hasil.getContentPane().add(labelberhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, -1));
        hasil.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 360, 10));

        labelpinjam4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelpinjam4.setForeground(new java.awt.Color(155, 164, 180));
        labelpinjam4.setText("PINJAM");
        hasil.getContentPane().add(labelpinjam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        labelberhasil1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelberhasil1.setForeground(new java.awt.Color(155, 164, 180));
        labelberhasil1.setText("BUKU BERHASIL");
        hasil.getContentPane().add(labelberhasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 290, -1));

        lagi.setBackground(new java.awt.Color(155, 164, 180));
        lagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lagi.setForeground(new java.awt.Color(255, 255, 255));
        lagi.setText("Pinjam Buku Lain");
        lagi.setBorder(null);
        lagi.setBorderPainted(false);
        lagi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasil.getContentPane().add(lagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 140, 40));

        labeltenggat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labeltenggat.setForeground(new java.awt.Color(155, 164, 180));
        labeltenggat.setText("Tenggat Pengembalian :");
        hasil.getContentPane().add(labeltenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        tenggat.setBackground(new java.awt.Color(216, 219, 227));
        tenggat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tenggat.setForeground(new java.awt.Color(155, 164, 180));
        tenggat.setText("tanggal/bulan/tahun");
        hasil.getContentPane().add(tenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 450));
        setMinimumSize(new java.awt.Dimension(830, 450));
        setPreferredSize(new java.awt.Dimension(830, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpinjam1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpinjam1.setForeground(new java.awt.Color(190, 196, 205));
        labelpinjam1.setText("PEMINJAMAN BUKU");
        getContentPane().add(labelpinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 360, 10));

        labelpinjam2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelpinjam2.setForeground(new java.awt.Color(155, 164, 180));
        labelpinjam2.setText("PINJAM");
        getContentPane().add(labelpinjam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        home1.setBackground(new java.awt.Color(241, 244, 246));
        home1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home1.setForeground(new java.awt.Color(255, 255, 255));
        home1.setText("HOME");
        home1.setBorderPainted(false);
        home1.setContentAreaFilled(false);
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota1.setBackground(new java.awt.Color(241, 244, 246));
        anggota1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota1.setForeground(new java.awt.Color(255, 255, 255));
        anggota1.setText("ANGGOTA");
        anggota1.setBorderPainted(false);
        anggota1.setContentAreaFilled(false);
        anggota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota1ActionPerformed(evt);
            }
        });
        getContentPane().add(anggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku1.setBackground(new java.awt.Color(241, 244, 246));
        buku1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku1.setForeground(new java.awt.Color(255, 255, 255));
        buku1.setText("BUKU");
        buku1.setBorderPainted(false);
        buku1.setContentAreaFilled(false);
        buku1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku1ActionPerformed(evt);
            }
        });
        getContentPane().add(buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman1.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman1.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman1.setText("PEMINJAMAN");
        peminjaman1.setBorderPainted(false);
        peminjaman1.setContentAreaFilled(false);
        peminjaman1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman1ActionPerformed(evt);
            }
        });
        getContentPane().add(peminjaman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian1.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian1.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian1.setText("PENGEMBALIAN");
        pengembalian1.setBorderPainted(false);
        pengembalian1.setContentAreaFilled(false);
        pengembalian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian1ActionPerformed(evt);
            }
        });
        getContentPane().add(pengembalian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini1.setBackground(new java.awt.Color(241, 244, 246));
        statkini1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini1.setForeground(new java.awt.Color(255, 255, 255));
        statkini1.setText("STATUS TERKINI");
        statkini1.setBorderPainted(false);
        statkini1.setContentAreaFilled(false);
        statkini1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini1ActionPerformed(evt);
            }
        });
        getContentPane().add(statkini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        riwayat1.setBackground(new java.awt.Color(241, 244, 246));
        riwayat1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        riwayat1.setForeground(new java.awt.Color(255, 255, 255));
        riwayat1.setText("RIWAYAT");
        riwayat1.setBorderPainted(false);
        riwayat1.setContentAreaFilled(false);
        riwayat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayat1ActionPerformed(evt);
            }
        });
        getContentPane().add(riwayat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 270, 150, -1));

        bg3.setBackground(new java.awt.Color(155, 164, 180));
        bg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali1.setForeground(new java.awt.Color(255, 255, 255));
        kembali1.setText("kembali");
        kembali1.setBorderPainted(false);
        kembali1.setContentAreaFilled(false);
        kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ActionPerformed(evt);
            }
        });
        bg3.add(kembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover1.setBackground(new java.awt.Color(190, 196, 205));
        hover1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg3.add(hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        labelidb.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelidb.setForeground(new java.awt.Color(155, 164, 180));
        labelidb.setText("ID Buku");
        getContentPane().add(labelidb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        labelidba.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelidba.setForeground(new java.awt.Color(155, 164, 180));
        labelidba.setText("ID Anggota");
        getContentPane().add(labelidba, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        inputidb.setBackground(new java.awt.Color(216, 219, 227));
        inputidb.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        inputidb.setForeground(new java.awt.Color(155, 164, 180));
        inputidb.setBorder(null);
        getContentPane().add(inputidb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 300, 30));

        inputida.setBackground(new java.awt.Color(216, 219, 227));
        inputida.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        inputida.setForeground(new java.awt.Color(155, 164, 180));
        inputida.setBorder(null);
        getContentPane().add(inputida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 300, 30));

        buttoncek.setBackground(new java.awt.Color(155, 164, 180));
        buttoncek.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttoncek.setForeground(new java.awt.Color(255, 255, 255));
        buttoncek.setText("Cek");
        buttoncek.setBorder(null);
        buttoncek.setBorderPainted(false);
        buttoncek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(buttoncek, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_kembali1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home1ActionPerformed

    private void anggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota1ActionPerformed

    private void buku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku1ActionPerformed

    private void peminjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjaman1ActionPerformed

    private void pengembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian1ActionPerformed

    private void statkini1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini1ActionPerformed

    private void riwayat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayat1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_riwayat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void pinjampage(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjampage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anggota1;
    private javax.swing.JButton anggota2;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel bg4;
    private javax.swing.JButton buku1;
    private javax.swing.JButton buku2;
    private javax.swing.JButton buttoncek;
    private javax.swing.JDialog hasil;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JTextField inputida;
    private javax.swing.JTextField inputidb;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kembali1;
    private javax.swing.JButton kembali2;
    private javax.swing.JLabel labelberhasil;
    private javax.swing.JLabel labelberhasil1;
    private javax.swing.JLabel labelidb;
    private javax.swing.JLabel labelidba;
    private javax.swing.JLabel labelpinjam1;
    private javax.swing.JLabel labelpinjam2;
    private javax.swing.JLabel labelpinjam3;
    private javax.swing.JLabel labelpinjam4;
    private javax.swing.JLabel labeltenggat;
    private javax.swing.JButton lagi;
    private javax.swing.JButton peminjaman1;
    private javax.swing.JButton peminjaman2;
    private javax.swing.JButton pengembalian1;
    private javax.swing.JButton pengembalian2;
    private javax.swing.JButton riwayat1;
    private javax.swing.JButton riwayat2;
    private javax.swing.JButton statkini1;
    private javax.swing.JButton statkini2;
    private javax.swing.JLabel tenggat;
    // End of variables declaration//GEN-END:variables
}
