package com.mycompany.perpusdata;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class pinjampage extends javax.swing.JFrame {

    /**
     * Creates new form pinjampage
     */
    public pinjampage() {
        initComponents();
        getContentPane().setBackground(Color.decode("0xFFFFFFF"));
        setDefaultCloseOperation(pinjampage.DISPOSE_ON_CLOSE);
        hasil.setDefaultCloseOperation(hasil.DISPOSE_ON_CLOSE);
        jDialog1.setDefaultCloseOperation(hasil.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        home3 = new javax.swing.JButton();
        anggota3 = new javax.swing.JButton();
        buku3 = new javax.swing.JButton();
        peminjaman3 = new javax.swing.JButton();
        pengembalian3 = new javax.swing.JButton();
        statkini3 = new javax.swing.JButton();
        bg5 = new javax.swing.JPanel();
        kembali3 = new javax.swing.JButton();
        hover3 = new javax.swing.JPanel();
        labelpinjam5 = new javax.swing.JLabel();
        labelida = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labeljenke = new javax.swing.JLabel();
        labelalamat = new javax.swing.JLabel();
        labelketentuan7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelcreate3 = new javax.swing.JLabel();
        labelidb2 = new javax.swing.JLabel();
        labeljudul = new javax.swing.JLabel();
        labelpenulis = new javax.swing.JLabel();
        labelpenerbit = new javax.swing.JLabel();
        labeljmlhalaman = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        labelemail1 = new javax.swing.JLabel();
        labelketentuan = new javax.swing.JLabel();
        labelketentuan2 = new javax.swing.JLabel();
        labelketentuan3 = new javax.swing.JLabel();
        labelketentuan4 = new javax.swing.JLabel();
        labelketentuan5 = new javax.swing.JLabel();
        labelketentuan6 = new javax.swing.JLabel();
        labelcreate4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labellanjutkan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonkembali = new javax.swing.JButton();
        buttonlanjutkan = new javax.swing.JButton();
        hasiljumha = new javax.swing.JLabel();
        hasilida = new javax.swing.JLabel();
        hasilnama = new javax.swing.JLabel();
        hasiljenke = new javax.swing.JLabel();
        hasilalamat = new javax.swing.JLabel();
        hasilemail = new javax.swing.JLabel();
        hasilidb = new javax.swing.JLabel();
        hasiljudul = new javax.swing.JLabel();
        hasilpenulis = new javax.swing.JLabel();
        hasilpenerbit = new javax.swing.JLabel();
        hasil = new javax.swing.JDialog();
        labelpinjam3 = new javax.swing.JLabel();
        home2 = new javax.swing.JButton();
        anggota2 = new javax.swing.JButton();
        buku2 = new javax.swing.JButton();
        peminjaman2 = new javax.swing.JButton();
        pengembalian2 = new javax.swing.JButton();
        statkini2 = new javax.swing.JButton();
        bg4 = new javax.swing.JPanel();
        kembali2 = new javax.swing.JButton();
        hover2 = new javax.swing.JPanel();
        labelberhasil = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelpinjam4 = new javax.swing.JLabel();
        labelberhasil1 = new javax.swing.JLabel();
        lagi = new javax.swing.JButton();
        labeltenggat = new javax.swing.JLabel();
        tenggat = new javax.swing.JLabel();
        labelpinjam1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelpinjam2 = new javax.swing.JLabel();
        home1 = new javax.swing.JButton();
        anggota1 = new javax.swing.JButton();
        buku1 = new javax.swing.JButton();
        peminjaman1 = new javax.swing.JButton();
        pengembalian1 = new javax.swing.JButton();
        statkini1 = new javax.swing.JButton();
        bg3 = new javax.swing.JPanel();
        kembali1 = new javax.swing.JButton();
        hover1 = new javax.swing.JPanel();
        labelidb = new javax.swing.JLabel();
        labelidba = new javax.swing.JLabel();
        inputidb = new javax.swing.JTextField();
        inputida = new javax.swing.JTextField();
        buttoncek = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(830, 450));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home3.setBackground(new java.awt.Color(241, 244, 246));
        home3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home3.setForeground(new java.awt.Color(255, 255, 255));
        home3.setText("HOME");
        home3.setBorderPainted(false);
        home3.setContentAreaFilled(false);
        home3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota3.setBackground(new java.awt.Color(241, 244, 246));
        anggota3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota3.setForeground(new java.awt.Color(255, 255, 255));
        anggota3.setText("ANGGOTA");
        anggota3.setBorderPainted(false);
        anggota3.setContentAreaFilled(false);
        anggota3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(anggota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku3.setBackground(new java.awt.Color(241, 244, 246));
        buku3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku3.setForeground(new java.awt.Color(255, 255, 255));
        buku3.setText("BUKU");
        buku3.setBorderPainted(false);
        buku3.setContentAreaFilled(false);
        buku3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(buku3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman3.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman3.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman3.setText("PEMINJAMAN");
        peminjaman3.setBorderPainted(false);
        peminjaman3.setContentAreaFilled(false);
        peminjaman3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(peminjaman3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian3.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian3.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian3.setText("PENGEMBALIAN");
        pengembalian3.setBorderPainted(false);
        pengembalian3.setContentAreaFilled(false);
        pengembalian3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(pengembalian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini3.setBackground(new java.awt.Color(241, 244, 246));
        statkini3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini3.setForeground(new java.awt.Color(255, 255, 255));
        statkini3.setText("STATUS TERKINI");
        statkini3.setBorderPainted(false);
        statkini3.setContentAreaFilled(false);
        statkini3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(statkini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        bg5.setBackground(new java.awt.Color(155, 164, 180));
        bg5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali3.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali3.setForeground(new java.awt.Color(255, 255, 255));
        kembali3.setText("logout");
        kembali3.setBorderPainted(false);
        kembali3.setContentAreaFilled(false);
        kembali3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali3ActionPerformed(evt);
            }
        });
        bg5.add(kembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover3.setBackground(new java.awt.Color(190, 196, 205));
        hover3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg5.add(hover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        jDialog1.getContentPane().add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        labelpinjam5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpinjam5.setForeground(new java.awt.Color(190, 196, 205));
        labelpinjam5.setText("PEMINJAMAN BUKU");
        jDialog1.getContentPane().add(labelpinjam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        labelida.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelida.setForeground(new java.awt.Color(155, 164, 180));
        labelida.setText("ID Anggota      :");
        jDialog1.getContentPane().add(labelida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        labelnama.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelnama.setForeground(new java.awt.Color(155, 164, 180));
        labelnama.setText("Nama                 :");
        jDialog1.getContentPane().add(labelnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        labeljenke.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labeljenke.setForeground(new java.awt.Color(155, 164, 180));
        labeljenke.setText("Jenis Kelamin  :");
        jDialog1.getContentPane().add(labeljenke, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        labelalamat.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelalamat.setForeground(new java.awt.Color(155, 164, 180));
        labelalamat.setText("Alamat              :");
        jDialog1.getContentPane().add(labelalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        labelketentuan7.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan7.setText("maksimal 2 buku");
        jDialog1.getContentPane().add(labelketentuan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        jDialog1.getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 160, -1));

        labelcreate3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelcreate3.setForeground(new java.awt.Color(155, 164, 180));
        labelcreate3.setText("BUKU");
        jDialog1.getContentPane().add(labelcreate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        labelidb2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelidb2.setForeground(new java.awt.Color(155, 164, 180));
        labelidb2.setText("ID Buku          :");
        jDialog1.getContentPane().add(labelidb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        labeljudul.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labeljudul.setForeground(new java.awt.Color(155, 164, 180));
        labeljudul.setText("Judul              :");
        jDialog1.getContentPane().add(labeljudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        labelpenulis.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpenulis.setForeground(new java.awt.Color(155, 164, 180));
        labelpenulis.setText("Penulis           :");
        jDialog1.getContentPane().add(labelpenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        labelpenerbit.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpenerbit.setForeground(new java.awt.Color(155, 164, 180));
        labelpenerbit.setText("Penerbit         :");
        jDialog1.getContentPane().add(labelpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        labeljmlhalaman.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labeljmlhalaman.setForeground(new java.awt.Color(155, 164, 180));
        labeljmlhalaman.setText("Jml Halaman :");
        jDialog1.getContentPane().add(labeljmlhalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));
        jDialog1.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 220, 10));

        labelemail1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelemail1.setForeground(new java.awt.Color(155, 164, 180));
        labelemail1.setText("Email                 :");
        jDialog1.getContentPane().add(labelemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        labelketentuan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelketentuan.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan.setText("Ketentuan Peminjaman:");
        jDialog1.getContentPane().add(labelketentuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        labelketentuan2.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan2.setText("1. Maksimal waktu peminjaman adalah 5 hari");
        jDialog1.getContentPane().add(labelketentuan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        labelketentuan3.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan3.setText("2. Akan dikenakan denda sebesar Rp.1000,-/hari");
        jDialog1.getContentPane().add(labelketentuan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        labelketentuan4.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan4.setText("dan tidak diperbolehkan mengajukan peminjaman");
        jDialog1.getContentPane().add(labelketentuan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        labelketentuan5.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan5.setText("selama dan bila melewati batas waktu");
        jDialog1.getContentPane().add(labelketentuan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        labelketentuan6.setForeground(new java.awt.Color(155, 164, 180));
        labelketentuan6.setText("3. Peminjam hanya dapat mengajukan peminjaman");
        jDialog1.getContentPane().add(labelketentuan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        labelcreate4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelcreate4.setForeground(new java.awt.Color(155, 164, 180));
        labelcreate4.setText("ANGGOTA");
        jDialog1.getContentPane().add(labelcreate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(155, 164, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellanjutkan.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        labellanjutkan.setForeground(new java.awt.Color(255, 255, 255));
        labellanjutkan.setText("LANJUTKAN?");
        jPanel1.add(labellanjutkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pastikan tidak ada kekeliruan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Periksa lagi data tujuan anda dan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        buttonkembali.setBackground(new java.awt.Color(190, 196, 205));
        buttonkembali.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttonkembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonkembali.setText("Kembali");
        buttonkembali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonkembali.setContentAreaFilled(false);
        buttonkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        buttonlanjutkan.setBackground(new java.awt.Color(190, 196, 205));
        buttonlanjutkan.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttonlanjutkan.setForeground(new java.awt.Color(255, 255, 255));
        buttonlanjutkan.setText("Lanjutkan");
        buttonlanjutkan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonlanjutkan.setContentAreaFilled(false);
        buttonlanjutkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlanjutkanActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlanjutkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        jDialog1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 270, 140));

        hasiljumha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasiljumha.setForeground(new java.awt.Color(155, 164, 180));
        hasiljumha.setText("ID Anggota");
        jDialog1.getContentPane().add(hasiljumha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 170, 20));

        hasilida.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilida.setForeground(new java.awt.Color(155, 164, 180));
        hasilida.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilida, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 170, 20));

        hasilnama.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilnama.setForeground(new java.awt.Color(155, 164, 180));
        hasilnama.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 170, 20));

        hasiljenke.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasiljenke.setForeground(new java.awt.Color(155, 164, 180));
        hasiljenke.setText("ID Anggota");
        jDialog1.getContentPane().add(hasiljenke, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, 20));

        hasilalamat.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilalamat.setForeground(new java.awt.Color(155, 164, 180));
        hasilalamat.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, 20));

        hasilemail.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilemail.setForeground(new java.awt.Color(155, 164, 180));
        hasilemail.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, 20));

        hasilidb.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilidb.setForeground(new java.awt.Color(155, 164, 180));
        hasilidb.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilidb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, 20));

        hasiljudul.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasiljudul.setForeground(new java.awt.Color(155, 164, 180));
        hasiljudul.setText("ID Anggota");
        jDialog1.getContentPane().add(hasiljudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 170, 20));

        hasilpenulis.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilpenulis.setForeground(new java.awt.Color(155, 164, 180));
        hasilpenulis.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilpenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 170, 20));

        hasilpenerbit.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        hasilpenerbit.setForeground(new java.awt.Color(155, 164, 180));
        hasilpenerbit.setText("ID Anggota");
        jDialog1.getContentPane().add(hasilpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 170, 20));

        hasil.setMinimumSize(new java.awt.Dimension(830, 450));
        hasil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpinjam3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpinjam3.setForeground(new java.awt.Color(190, 196, 205));
        labelpinjam3.setText("PEMINJAMAN BUKU");
        hasil.getContentPane().add(labelpinjam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        home2.setBackground(new java.awt.Color(241, 244, 246));
        home2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home2.setForeground(new java.awt.Color(255, 255, 255));
        home2.setText("HOME");
        home2.setBorderPainted(false);
        home2.setContentAreaFilled(false);
        home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota2.setBackground(new java.awt.Color(241, 244, 246));
        anggota2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota2.setForeground(new java.awt.Color(255, 255, 255));
        anggota2.setText("ANGGOTA");
        anggota2.setBorderPainted(false);
        anggota2.setContentAreaFilled(false);
        anggota2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(anggota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku2.setBackground(new java.awt.Color(241, 244, 246));
        buku2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku2.setForeground(new java.awt.Color(255, 255, 255));
        buku2.setText("BUKU");
        buku2.setBorderPainted(false);
        buku2.setContentAreaFilled(false);
        buku2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(buku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman2.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman2.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman2.setText("PEMINJAMAN");
        peminjaman2.setBorderPainted(false);
        peminjaman2.setContentAreaFilled(false);
        peminjaman2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(peminjaman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian2.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian2.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian2.setText("PENGEMBALIAN");
        pengembalian2.setBorderPainted(false);
        pengembalian2.setContentAreaFilled(false);
        pengembalian2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(pengembalian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini2.setBackground(new java.awt.Color(241, 244, 246));
        statkini2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini2.setForeground(new java.awt.Color(255, 255, 255));
        statkini2.setText("STATUS TERKINI");
        statkini2.setBorderPainted(false);
        statkini2.setContentAreaFilled(false);
        statkini2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini2ActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(statkini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        bg4.setBackground(new java.awt.Color(155, 164, 180));
        bg4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali2.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali2.setForeground(new java.awt.Color(255, 255, 255));
        kembali2.setText("logout");
        kembali2.setBorderPainted(false);
        kembali2.setContentAreaFilled(false);
        kembali2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali2ActionPerformed(evt);
            }
        });
        bg4.add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover2.setBackground(new java.awt.Color(190, 196, 205));
        hover2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg4.add(hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        hasil.getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        labelberhasil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelberhasil.setForeground(new java.awt.Color(155, 164, 180));
        labelberhasil.setText("DIPINJAM");
        hasil.getContentPane().add(labelberhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, -1));
        hasil.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 360, 10));

        labelpinjam4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelpinjam4.setForeground(new java.awt.Color(155, 164, 180));
        labelpinjam4.setText("PINJAM");
        hasil.getContentPane().add(labelpinjam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        labelberhasil1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelberhasil1.setForeground(new java.awt.Color(155, 164, 180));
        labelberhasil1.setText("BUKU BERHASIL");
        hasil.getContentPane().add(labelberhasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 290, -1));

        lagi.setBackground(new java.awt.Color(155, 164, 180));
        lagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lagi.setForeground(new java.awt.Color(255, 255, 255));
        lagi.setText("Pinjam Buku Lain");
        lagi.setBorder(null);
        lagi.setBorderPainted(false);
        lagi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lagiActionPerformed(evt);
            }
        });
        hasil.getContentPane().add(lagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 140, 40));

        labeltenggat.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labeltenggat.setForeground(new java.awt.Color(155, 164, 180));
        labeltenggat.setText("Tenggat Pengembalian :");
        hasil.getContentPane().add(labeltenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        tenggat.setBackground(new java.awt.Color(216, 219, 227));
        tenggat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tenggat.setForeground(new java.awt.Color(155, 164, 180));
        tenggat.setText("tanggal/bulan/tahun");
        hasil.getContentPane().add(tenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpinjam1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelpinjam1.setForeground(new java.awt.Color(190, 196, 205));
        labelpinjam1.setText("PEMINJAMAN BUKU");
        getContentPane().add(labelpinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 360, 10));

        labelpinjam2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelpinjam2.setForeground(new java.awt.Color(155, 164, 180));
        labelpinjam2.setText("PINJAM");
        getContentPane().add(labelpinjam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        home1.setBackground(new java.awt.Color(241, 244, 246));
        home1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        home1.setForeground(new java.awt.Color(255, 255, 255));
        home1.setText("HOME");
        home1.setBorderPainted(false);
        home1.setContentAreaFilled(false);
        home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        getContentPane().add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        anggota1.setBackground(new java.awt.Color(241, 244, 246));
        anggota1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        anggota1.setForeground(new java.awt.Color(255, 255, 255));
        anggota1.setText("ANGGOTA");
        anggota1.setBorderPainted(false);
        anggota1.setContentAreaFilled(false);
        anggota1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggota1ActionPerformed(evt);
            }
        });
        getContentPane().add(anggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        buku1.setBackground(new java.awt.Color(241, 244, 246));
        buku1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buku1.setForeground(new java.awt.Color(255, 255, 255));
        buku1.setText("BUKU");
        buku1.setBorderPainted(false);
        buku1.setContentAreaFilled(false);
        buku1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku1ActionPerformed(evt);
            }
        });
        getContentPane().add(buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 120, 20));

        peminjaman1.setBackground(new java.awt.Color(241, 244, 246));
        peminjaman1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        peminjaman1.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman1.setText("PEMINJAMAN");
        peminjaman1.setBorderPainted(false);
        peminjaman1.setContentAreaFilled(false);
        peminjaman1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjaman1ActionPerformed(evt);
            }
        });
        getContentPane().add(peminjaman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 30));

        pengembalian1.setBackground(new java.awt.Color(241, 244, 246));
        pengembalian1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pengembalian1.setForeground(new java.awt.Color(255, 255, 255));
        pengembalian1.setText("PENGEMBALIAN");
        pengembalian1.setBorderPainted(false);
        pengembalian1.setContentAreaFilled(false);
        pengembalian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalian1ActionPerformed(evt);
            }
        });
        getContentPane().add(pengembalian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        statkini1.setBackground(new java.awt.Color(241, 244, 246));
        statkini1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        statkini1.setForeground(new java.awt.Color(255, 255, 255));
        statkini1.setText("STATUS TERKINI");
        statkini1.setBorderPainted(false);
        statkini1.setContentAreaFilled(false);
        statkini1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statkini1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statkini1ActionPerformed(evt);
            }
        });
        getContentPane().add(statkini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, -1));

        bg3.setBackground(new java.awt.Color(155, 164, 180));
        bg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        kembali1.setForeground(new java.awt.Color(255, 255, 255));
        kembali1.setText("logout");
        kembali1.setBorderPainted(false);
        kembali1.setContentAreaFilled(false);
        kembali1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ActionPerformed(evt);
            }
        });
        bg3.add(kembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, -1, -1));

        hover1.setBackground(new java.awt.Color(190, 196, 205));
        hover1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg3.add(hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 30));

        getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        labelidb.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelidb.setForeground(new java.awt.Color(155, 164, 180));
        labelidb.setText("ID Buku");
        getContentPane().add(labelidb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        labelidba.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelidba.setForeground(new java.awt.Color(155, 164, 180));
        labelidba.setText("ID Anggota");
        getContentPane().add(labelidba, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        inputidb.setBackground(new java.awt.Color(216, 219, 227));
        inputidb.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        inputidb.setForeground(new java.awt.Color(155, 164, 180));
        inputidb.setBorder(null);
        getContentPane().add(inputidb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 300, 30));

        inputida.setBackground(new java.awt.Color(216, 219, 227));
        inputida.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        inputida.setForeground(new java.awt.Color(155, 164, 180));
        inputida.setBorder(null);
        getContentPane().add(inputida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 300, 30));

        buttoncek.setBackground(new java.awt.Color(155, 164, 180));
        buttoncek.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        buttoncek.setForeground(new java.awt.Color(255, 255, 255));
        buttoncek.setText("Cek");
        buttoncek.setBorder(null);
        buttoncek.setBorderPainted(false);
        buttoncek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncekActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncek, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembali1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home1ActionPerformed

    private void anggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota1ActionPerformed

    private void buku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku1ActionPerformed

    private void peminjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjaman1ActionPerformed

    private void pengembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian1ActionPerformed

    private void statkini1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini1ActionPerformed

    public void tampilDataAnggota(int id_anggota){
        String query = "SELECT id_anggota, nama, jenis_kelamin, alamat, email FROM anggota WHERE id_anggota = ?";
        try{
            Koneksi konek = new Koneksi();
            Connection koneksi = konek.buka();
            PreparedStatement preparedStatement = koneksi.prepareStatement(query);
            preparedStatement.setInt(1, id_anggota);
            
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    // Ambil data dari ResultSet dan set pada JLabels
                    hasilida.setText("" + resultSet.getInt("id_anggota"));
                    hasilnama.setText(resultSet.getString("nama"));
                    hasiljenke.setText(resultSet.getString("jenis_kelamin"));
                    hasilalamat.setText(resultSet.getString("alamat"));
                    hasilemail.setText(resultSet.getString("email"));
                } else {
                    System.out.println("Data tidak ditemukan.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void tampilDataBuku(int id_buku){
        String query = "SELECT id_buku, judul, penulis, penerbit, jumlah_halaman FROM buku WHERE id_buku= ?";
        try{
            Koneksi konek = new Koneksi();
            Connection koneksi = konek.buka();
            PreparedStatement preparedStatement = koneksi.prepareStatement(query);
            preparedStatement.setInt(1, id_buku);
            
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    // Ambil data dari ResultSet dan set pada JLabels
                    hasilidb.setText("" + resultSet.getInt("id_buku"));
                    hasiljudul.setText(resultSet.getString("judul"));
                    hasilpenulis.setText(resultSet.getString("penulis"));
                    hasilpenerbit.setText(resultSet.getString("penerbit"));
                    hasiljumha.setText(resultSet.getString("jumlah_halaman"));
                } else {
                    System.out.println("Data tidak ditemukan.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void buttoncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncekActionPerformed
        // TODO add your handling code here:
        try{
            int id_anggota = Integer.parseInt(inputida.getText());
            int id_buku = Integer.parseInt(inputidb.getText());
            Peminjaman pinjam = new Peminjaman();
                if (pinjam.cekAnggota(id_anggota) && pinjam.cekBuku(id_buku)) {
                    dispose();
                    jDialog1.setVisible(true);
                    jDialog1.getContentPane().setBackground(Color.decode("0xFFFFFF"));
                    this.tampilDataAnggota(id_anggota);
                    this.tampilDataBuku(id_buku);
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Masukkan angka atau integer saja", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } /*catch(SQLException e) {
            e.printStackTrace(); } */
    }//GEN-LAST:event_buttoncekActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home3ActionPerformed

    private void anggota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota3ActionPerformed

    private void buku3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku3ActionPerformed

    private void peminjaman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_peminjaman3ActionPerformed

    private void pengembalian3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian3ActionPerformed

    private void statkini3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini3ActionPerformed

    private void kembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali3ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembali3ActionPerformed

    private void buttonkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkembaliActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_buttonkembaliActionPerformed

    private void buttonlanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlanjutkanActionPerformed
        // TODO add your handling code here:
        int id_anggota = Integer.parseInt(inputida.getText());
        int id_buku = Integer.parseInt(inputidb.getText());
        Peminjaman pinjam = new Peminjaman();
        IDGenerator id = new IDGenerator();
        int id_transaksi = id.idGenerator();
        pinjam.catatPeminjaman(id_transaksi, id_anggota, id_buku);
        tenggat.setText(pinjam.cekTenggat());
        jDialog1.dispose();
        hasil.setVisible(true);
        hasil.getContentPane().setBackground(Color.decode("0xFFFFFF"));
    }//GEN-LAST:event_buttonlanjutkanActionPerformed

    private void lagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lagiActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_lagiActionPerformed

    private void kembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new loginform().setVisible(true);
    }//GEN-LAST:event_kembali2ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_home2ActionPerformed

    private void anggota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggota2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new anggotapage().setVisible(true);
    }//GEN-LAST:event_anggota2ActionPerformed

    private void buku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new bukupage().setVisible(true);
    }//GEN-LAST:event_buku2ActionPerformed

    private void peminjaman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjaman2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new pinjampage().setVisible(true);
    }//GEN-LAST:event_peminjaman2ActionPerformed

    private void pengembalian2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalian2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new kembalipage().setVisible(true);
    }//GEN-LAST:event_pengembalian2ActionPerformed

    private void statkini2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statkini2ActionPerformed
        // TODO add your handling code here:
        hasil.dispose();
        new statuspage().setVisible(true);
    }//GEN-LAST:event_statkini2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void pinjampage(String args[]) {
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjampage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjampage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anggota1;
    private javax.swing.JButton anggota2;
    private javax.swing.JButton anggota3;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel bg4;
    private javax.swing.JPanel bg5;
    private javax.swing.JButton buku1;
    private javax.swing.JButton buku2;
    private javax.swing.JButton buku3;
    private javax.swing.JButton buttoncek;
    private javax.swing.JButton buttonkembali;
    private javax.swing.JButton buttonlanjutkan;
    private javax.swing.JDialog hasil;
    private javax.swing.JLabel hasilalamat;
    private javax.swing.JLabel hasilemail;
    private javax.swing.JLabel hasilida;
    private javax.swing.JLabel hasilidb;
    private javax.swing.JLabel hasiljenke;
    private javax.swing.JLabel hasiljudul;
    private javax.swing.JLabel hasiljumha;
    private javax.swing.JLabel hasilnama;
    private javax.swing.JLabel hasilpenerbit;
    private javax.swing.JLabel hasilpenulis;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JButton home3;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JPanel hover3;
    private javax.swing.JTextField inputida;
    private javax.swing.JTextField inputidb;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton kembali1;
    private javax.swing.JButton kembali2;
    private javax.swing.JButton kembali3;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labelberhasil;
    private javax.swing.JLabel labelberhasil1;
    private javax.swing.JLabel labelcreate3;
    private javax.swing.JLabel labelcreate4;
    private javax.swing.JLabel labelemail1;
    private javax.swing.JLabel labelida;
    private javax.swing.JLabel labelidb;
    private javax.swing.JLabel labelidb2;
    private javax.swing.JLabel labelidba;
    private javax.swing.JLabel labeljenke;
    private javax.swing.JLabel labeljmlhalaman;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labelketentuan;
    private javax.swing.JLabel labelketentuan2;
    private javax.swing.JLabel labelketentuan3;
    private javax.swing.JLabel labelketentuan4;
    private javax.swing.JLabel labelketentuan5;
    private javax.swing.JLabel labelketentuan6;
    private javax.swing.JLabel labelketentuan7;
    private javax.swing.JLabel labellanjutkan;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelpenerbit;
    private javax.swing.JLabel labelpenulis;
    private javax.swing.JLabel labelpinjam1;
    private javax.swing.JLabel labelpinjam2;
    private javax.swing.JLabel labelpinjam3;
    private javax.swing.JLabel labelpinjam4;
    private javax.swing.JLabel labelpinjam5;
    private javax.swing.JLabel labeltenggat;
    private javax.swing.JButton lagi;
    private javax.swing.JButton peminjaman1;
    private javax.swing.JButton peminjaman2;
    private javax.swing.JButton peminjaman3;
    private javax.swing.JButton pengembalian1;
    private javax.swing.JButton pengembalian2;
    private javax.swing.JButton pengembalian3;
    private javax.swing.JButton statkini1;
    private javax.swing.JButton statkini2;
    private javax.swing.JButton statkini3;
    private javax.swing.JLabel tenggat;
    // End of variables declaration//GEN-END:variables
}
